export type EntityCliqueRetire = Root2[]

export interface Root2 {
  DeliveredDate: any
  UrlRastreio: any
  CourierName: any
  FinishedCourier: boolean
  address_type: any
  arquivo_termo: any
  chapaColaborador: any
  cod_status: number
  cod_teste: any
  customer_address_number: any
  customer_bs64_biometry: string
  customer_bs64_signature: any
  customer_city: any
  customer_cpf: string
  customer_cpf_pickup: string
  customer_email: string
  customer_name: string
  customer_name_received: any
  customer_neighborhood: any
  customer_phone: string
  customer_postalcode: any
  customer_state: any
  customer_street: any
  data_evento_retirada: any
  data_hora_evento_retirada: any
  entrega_termo: any
  estimate_shipping_in_store: string
  id_order: string
  id_store_pickup: string
  invoice_key: string
  is_shipping_company: any
  is_shipping_employee: any
  is_shipping_from_store: any
  is_third_pickup: any
  item_uniforme: any
  lock_in_chapa: string
  lock_in_date: string
  lock_number: string
  lock_out_chapa: string
  lock_out_date: string
  lock_region: string
  nfe_order: string
  notification_estimate_shipping_in_store: any
  notification_out_limit_date: any
  order_has_techno: any
  order_techitem_island: any
  paymentSystemName: any
  pedido_Tratado: any
  qrCode: any
  search: any
  seller_chapa: any
  send_nps: any
  send_workchat: any
  status: string
  store_address: string
  third_pickup_cpf: any
  tracking_code: string
  id: string
  accountId: string
  accountName: string
  dataEntityId: string
  createdBy: string
  createdIn: string
  updatedBy: string
  updatedIn: string
  lastInteractionBy: string
  lastInteractionIn: string
  followers: any[]
  tags: any[]
  auto_filter: any
}
